name: release

on:
  release:
    types:
      - created

jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    strategy:
        matrix:
          name: [main-linux-amd64, main-darwin-amd64, main-darwin-arm64]
          include:
            - name: hakuna-go-linux-amd64
              os: linux
              arch: amd64
            - name: hakuan-go-macos-amd64
              os: darwin
              arch: amd64
            - name: hakuan-go-macos-arm64
              os: darwin
              arch: arm64

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: go build -o ./dist/${{ matrix.name }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      # step 3: upload build-artifacts
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/hakuna-go*"
