name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  releases:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --tags -f

      - name: Resolve version
        id: vars
        run: echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build binaries
        run: make all

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ steps.vars.outputs.tag_name }}
          body: |
            * [Linux (arm64)](https://github.com/hdahlheim/hakuna-go/releases/download/${{ steps.vars.outputs.tag_name }}/hakuna-go-linux-arm64)
            * [Linux (amd64)](https://github.com/hdahlheim/hakuna-go/releases/download/${{ steps.vars.outputs.tag_name }}/hakuna-go-linux-amd64)
            * [macOS (arm64)](https://github.com/hdahlheim/hakuna-go/releases/download/${{ steps.vars.outputs.tag_name }}/hakuna-go-macos-arm64)
            * [macOS (amd64)](https://github.com/hdahlheim/hakuna-go/releases/download/${{ steps.vars.outputs.tag_name }}/hakuna-go-macos-amd64)

          files: |
            dist/hakuna-go-linux-arm64
            dist/hakuna-go-linux-arm64-md5
            dist/hakuna-go-linux-amd64
            dist/hakuna-go-linux-amd64-md5
            dist/hakuna-go-macos-arm64
            dist/hakuna-go-macos-arm64-md5
            dist/hakuna-go-macos-amd64
            dist/hakuna-go-macos-amd64-md5
