name: release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: linux
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          goversion: "1.17"
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          md5sum: TRUE
          asset_name: hakuna-go-${{ matrix.goos }}-${{ matrix.goarch }}
